spring.application.name=FileStorage
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5441/file_storage
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.data.redis.url=redis://localhost:6379

minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
